name: cicicd

on:
  push:
    paths:
      - src/**
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-6)" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            saagarsvs/python-app:latest
            saagarsvs/python-app:${{ steps.vars.outputs.SHORT_SHA }}
  cd:
    runs-on: self-hosted
    steps:

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd.test.com --password ${{ secrets.ARGOCD_PASSWORD }} --username {{ var.ARGOCD_USERNAME }} --insecure
          argocd app sync python-app1
          